// @vitest-environment node
import { afterEach, describe, expect, it, vi } from 'vitest';
import { subscribeSunsets, sunsetsSubscriptionAvailability } from '../services/sunsets-subscriptions';
const original={...process.env};
afterEach(()=>{process.env={...original};vi.unstubAllGlobals();});
const input={email:'Fan@example.com',audience:'event',consent:true,website:''};
function configure(){process.env.SUNSETS_SIGNUP_PROVIDER='flodesk';process.env.SUNSETS_FLODESK_API_KEY='test';process.env.SUNSETS_FLODESK_EVENT_SEGMENT='show';process.env.SUNSETS_FLODESK_RADIO_SEGMENT='radio';}
describe('Sunsets consent and provider delivery',()=>{
 it('does not report success when unconfigured or audiences overlap',async()=>{delete process.env.SUNSETS_SIGNUP_PROVIDER;expect(sunsetsSubscriptionAvailability().event).toBe(false);expect((await subscribeSunsets(input)).status).toBe(503);configure();process.env.SUNSETS_FLODESK_RADIO_SEGMENT='show';expect((await subscribeSunsets(input)).status).toBe(503);});
 it('requires valid email and consent and rejects the honeypot before any provider call',async()=>{configure();const fetch=vi.fn();vi.stubGlobal('fetch',fetch);for(const value of [{...input,consent:false},{...input,email:'bad'},{...input,website:'bot'},{...input,audience:'all'}])expect((await subscribeSunsets(value)).status).toBe(400);expect(fetch).not.toHaveBeenCalled();});
 it('upserts repeat emails in only the selected audience and requests double opt-in',async()=>{configure();const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>({id:'123',status:'active',segments:[{id:'show'}]})});vi.stubGlobal('fetch',fetch);expect((await subscribeSunsets(input)).body.ok).toBe(true);expect((await subscribeSunsets(input)).body.ok).toBe(true);expect(JSON.parse(fetch.mock.calls[0][1].body)).toEqual({email:'fan@example.com',segment_ids:['show'],double_optin:true});fetch.mockResolvedValue({ok:true,json:async()=>({id:'123',status:'active',segments:[{id:'radio'}]})});expect((await subscribeSunsets({...input,audience:'radio'})).body.ok).toBe(true);expect(JSON.parse(fetch.mock.calls[2][1].body).segment_ids).toEqual(['radio']);});
 it('distinguishes pending confirmation and suppressed addresses from active subscriptions',async()=>{configure();const fetch=vi.fn();vi.stubGlobal('fetch',fetch);fetch.mockResolvedValue({ok:true,json:async()=>({id:'123',status:'unconfirmed',segments:[{id:'show'}]})});expect((await subscribeSunsets(input)).body.state).toBe('confirmation_required');fetch.mockResolvedValue({ok:true,json:async()=>({id:'123',status:'unsubscribed',segments:[{id:'show'}]})});expect((await subscribeSunsets(input)).status).toBe(409);});
 it('never reports success for provider errors, malformed response or missing audience',async()=>{configure();const fetch=vi.fn();vi.stubGlobal('fetch',fetch);for(const response of [{ok:false},{ok:true,json:async()=>({id:'123',status:'active',segments:[]})},{ok:true,json:async()=>{throw new Error('secret provider error')}}]){fetch.mockResolvedValue(response);const result=await subscribeSunsets(input);expect(result.status).toBe(502);expect(JSON.stringify(result)).not.toContain('secret provider');}fetch.mockRejectedValue(new Error('timeout'));expect((await subscribeSunsets(input)).status).toBe(502);});
});
