import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { dirname, resolve } from "node:path";

const outputPath = resolve("shared/generated/hardening.ts");
const rotate = process.argv.includes("--rotate");
const explicitFieldName = process.env.MONOLITH_HONEYPOT_FIELD_NAME?.trim();

function readCurrentFieldName() {
  if (!existsSync(outputPath)) return null;

  const source = readFileSync(outputPath, "utf8");
  const match = source.match(/export const honeypotFieldName = "([^"]+)"/);
  return match?.[1] || null;
}

function buildFieldName() {
  if (explicitFieldName) return explicitFieldName;
  if (!rotate) return readCurrentFieldName() || "hp_bootstrap";
  return `hp_${randomBytes(6).toString("hex")}`;
}

const honeypotFieldName = buildFieldName();
const nextSource = `// Generated by scripts/sync_hardening_constants.mjs
export const honeypotFieldName = "${honeypotFieldName}" as const;
export type HoneypotPayload = Partial<Record<typeof honeypotFieldName, string>>;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, nextSource, "utf8");
